### ISSUE TITLE
issue with pyfiglet

### ISSUE THREAD

**Issue by Darkcast** [aqeisi/WP-RestScan#1]
Running macOS on M1
Python3.11
installed pyfiglet 0.8.post1

ps. looks like a weird font issue.

```
python3 WP-RestScan.py -h
Traceback (most recent call last):
  File "/Users/mr.pink/gitapps/WP-RestScan/WP-RestScan.py", line 166, in <module>
    banner()
  File "/Users/mr.pink/gitapps/WP-RestScan/WP-RestScan.py", line 54, in banner
    banner = Figlet(font='future')
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pyfiglet/__init__.py", line 794, in __init__
    self.setFont()
  File "/opt/homebrew/lib/python3.11/site-packages/pyfiglet/__init__.py", line 801, in setFont
    self.Font = FigletFont(font=self.font)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pyfiglet/__init__.py", line 126, in __init__
    self.data = self.preloadFont(font)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pyfiglet/__init__.py", line 147, in preloadFont
    raise FontNotFound(font)
pyfiglet.FontNotFound: future
```

**Comment by Darkcast** [comment]
So the issue is with mac and the version of pyglet lib. I made some change to the code if you want to import it, it makes it more unversal since it uses base64 for the banner.

```
import base64

def base64_to_ascii_banner(encoded_string):
    try:
        decoded_bytes = base64.b64decode(encoded_string)
        decoded_str = decoded_bytes.decode('utf-8', errors='ignore')
        print(decoded_str)
    except Exception as e:
        print("Error decoding base64: ", str(e))

# replace with your own based64 encoded banner
encoded_string = 'CuKWkuKWiOKWkeKWkeKWkuKWiCDilpLilojiloDiloDilogg4paR4paRIOKWkuKWiOKWgOKWgOKWiCDilojiloDiloAg4paI4paA4paAIOKWgOKWgOKWiOKWgOKWgCDilpLilojiloDiloDiloDilogg4paI4paA4paAIOKWiOKWgOKWgOKWiCDilojiloDiloDiloQgCuKWkuKWiOKWkuKWiOKWkuKWiCDilpLilojiloTiloTilogg4paA4paAIOKWkuKWiOKWhOKWhOKWgCDilojiloDiloAg4paA4paA4paIIOKWkeKWkeKWiOKWkeKWkSDilpHiloDiloDiloDiloTiloQg4paI4paR4paRIOKWiOKWhOKWhOKWiCDilojilpHilpHiloggCuKWkuKWiOKWhOKWgOKWhOKWiCDilpLilojilpHilpHilpEg4paR4paRIOKWkuKWiOKWkeKWkuKWiCDiloDiloDiloAg4paA4paA4paAIOKWkeKWkeKWgOKWkeKWkSDilpLilojiloTiloTiloTilogg4paA4paA4paAIOKWgOKWkeKWkeKWgCDiloDilpHilpHiloA='
base64_to_ascii_banner(encoded_string)

```

**Comment by Itay602** [comment]
fix it by change the "future" font in the code 
in line 54 banner = Figlet(Font = 'future) change it to 'standart'

**Comment by aqeisi** [comment]
Thank you for noting guys. Should be fixed now
